# Generated by Django 5.0.7 on 2024-08-05 14:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('headline', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('by', models.CharField(default='Maria Gabriela', max_length=100)),
                ('made_date', models.DateField(default=datetime.date.today)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
